# Phase 371A -- SGFX Pack Exporter.
#
# Produces a complete SGFX override pack at -OutputDir, ready to be
# consumed by an UnleashedRecomp build with SG_PREFLIGHT_OVERRIDE_DIR
# pointing at it. Replaces the previous "stitch a pack by hand"
# workflow that the proof runners (phase370b/c) inline.
#
# Layout produced:
#
#   <OutputDir>/
#     sgfx_pack.json            -- index (branding + lane paths)
#     pack_meta.json            -- ticket / project / phase metadata
#     text/sgfx_text.json       -- scoped CSD text rules
#     pictures/sgfx_pictures.json
#     pictures/<copies>         -- DDS files referenced by the manifest
#     sgfx_branding/icon.png    -- window icon (PNG, decoded by stb_image)
#     sgfx_branding/logo.png    -- decorative; reserved for in-game panel
#     loose/<...>               -- explicit loose-file substitutions
#     pack_export.log           -- audit trail of what was written
#
# This script is pure PowerShell (no Python dependency) so it can be
# called by a one-click launcher without spinning up sg-preflight's
# Python venv. sg-preflight can call this script directly, or feed
# it a -ScopedRulesJson path that it generated from its own model.
#
# Examples:
#   # Minimal (default branding, no scoped rules, no pixel overrides):
#   .\sgfx_pack_exporter.ps1 -OutputDir "$env:LOCALAPPDATA\UnleashedRecomp\sg_overrides_sgfx_shell"
#
#   # Full QA-ticket pack:
#   .\sgfx_pack_exporter.ps1 `
#       -OutputDir "$env:LOCALAPPDATA\UnleashedRecomp\sg_overrides_qa" `
#       -Ticket "IDCEVODEV-960073" `
#       -Project "BMW SGFX QA Shell" `
#       -ScopedRulesJson "C:\path\to\scoped_rules.json" `
#       -LogoSonicteamReplacement "C:\path\to\bmw_logo.dds" `
#       -Force

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$OutputDir,

    [string]$Ticket = '',
    [string]$Project = '',
    [string]$Phase = '371A',

    [string]$PackName = 'SGFX QA Shell Pack',
    [string]$PackDescription = 'Generated by sgfx_pack_exporter.ps1',

    [string]$WindowTitle = '',
    [string]$BuildLabel = '',

    [string]$IconPath = '',
    [string]$LogoPath = '',

    # When set, the in-game `logo_sonicteam` picture is replaced
    # with this DDS file. This is the simplest way to verify the
    # pack is live: the Title screen logo flips to the operator's
    # branding asset.
    [string]$LogoSonicteamReplacement = '',

    # Path to a JSON file containing a scoped-rules array, e.g.:
    #   [{ "literal":"99","csd_project_substring":"status",
    #      "replacement":"BMW QA 99" }, ... ]
    # Or a JSON object matching the full sg_text_overrides v2
    # schema (`{ "version":2, "strings": {}, "scoped_rules": [...] }`).
    [string]$ScopedRulesJson = '',

    # Optional explicit loose-file substitutions:
    #   @( @{ Guest='Loading/logo_sonicteam.dds'; Source='C:\..\bmw.dds' } )
    [object[]]$LooseFiles = @(),

    [string]$RepoRoot = '',

    [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Get-FullPathNoCreate([string]$Path) {
    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw "Path is empty"
    }
    return [System.IO.Path]::GetFullPath($Path)
}

function Test-PathIsSame([string]$Left, [string]$Right) {
    $a = (Get-FullPathNoCreate $Left).TrimEnd('\','/')
    $b = (Get-FullPathNoCreate $Right).TrimEnd('\','/')
    return [string]::Equals($a, $b, [System.StringComparison]::OrdinalIgnoreCase)
}

function Assert-SafeOutputDirectory([string]$Path, [string]$RepoRootPath) {
    $full = Get-FullPathNoCreate $Path
    $root = [System.IO.Path]::GetPathRoot($full)
    if (Test-PathIsSame $full $root) {
        throw "Refusing to use drive root as OutputDir: $full"
    }
    if ($env:USERPROFILE -and (Test-PathIsSame $full $env:USERPROFILE)) {
        throw "Refusing to use the user profile root as OutputDir: $full"
    }
    if ($RepoRootPath -and (Test-PathIsSame $full $RepoRootPath)) {
        throw "Refusing to use the repo root as OutputDir: $full"
    }
    return $full
}

function Resolve-PackChildPath([string]$BaseDir, [string]$RelativePath) {
    if ([string]::IsNullOrWhiteSpace($RelativePath)) {
        throw "Pack-relative path is empty"
    }
    if ([System.IO.Path]::IsPathRooted($RelativePath)) {
        throw "Pack-relative path must not be absolute: $RelativePath"
    }
    $parts = $RelativePath -split '[\\/]+' | Where-Object { $_ -ne '' }
    if (($parts | Where-Object { $_ -eq '..' }).Count -gt 0) {
        throw "Pack-relative path must not contain '..': $RelativePath"
    }
    $normalizedRelative = ($parts -join [System.IO.Path]::DirectorySeparatorChar)
    $baseFull = (Get-FullPathNoCreate $BaseDir).TrimEnd('\','/') + [System.IO.Path]::DirectorySeparatorChar
    $candidate = Get-FullPathNoCreate (Join-Path $BaseDir $normalizedRelative)
    if (-not $candidate.StartsWith($baseFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Pack-relative path escapes base directory: $RelativePath"
    }
    return $candidate
}

# --- 0. Locate repo root + default branding assets -----------------------

if (-not $RepoRoot -or $RepoRoot -eq '') {
    # Script lives at <repo>\research_uiux\runtime_reference\tools\.
    $scriptDir = Split-Path -Parent $PSCommandPath
    $RepoRoot  = (Resolve-Path (Join-Path $scriptDir '..\..\..')).ProviderPath
}
if (-not (Test-Path -LiteralPath $RepoRoot)) {
    throw "RepoRoot not found: $RepoRoot"
}

$OutputDir = Assert-SafeOutputDirectory -Path $OutputDir -RepoRootPath $RepoRoot

$resDir = Join-Path $RepoRoot 'res'

if (-not $IconPath -or $IconPath -eq '') {
    $IconPath = Join-Path $resDir 'sgfx_icon.png'
}
if (-not $LogoPath -or $LogoPath -eq '') {
    $LogoPath = Join-Path $resDir 'logo_sgfx.png'
}
if (-not $LogoSonicteamReplacement -or $LogoSonicteamReplacement -eq '') {
    $LogoSonicteamReplacement = Join-Path $resDir 'logo_sgfx.dds'
}

# Default WindowTitle / BuildLabel derive from ticket if provided so
# the operator does not have to type them every time.
if (-not $WindowTitle -or $WindowTitle -eq '') {
    if ($Ticket -ne '') {
        $WindowTitle = "SGFX QA Shell -- $Ticket"
    } else {
        $WindowTitle = 'SGFX QA Shell'
    }
}
if (-not $BuildLabel -or $BuildLabel -eq '') {
    $BuildLabel = "SGFX 0.5 (Phase $Phase)"
}

# --- 1. Reset OutputDir if -Force, otherwise create -----------------------

if (Test-Path -LiteralPath $OutputDir) {
    if ($Force) {
        Remove-Item -LiteralPath $OutputDir -Recurse -Force
    }
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$logLines = New-Object System.Collections.Generic.List[string]
function Add-Log([string]$msg) {
    $stamped = ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss.fff'), $msg)
    $logLines.Add($stamped)
    Write-Host $stamped
}

Add-Log "OutputDir = $OutputDir"
Add-Log "RepoRoot  = $RepoRoot"
Add-Log "Ticket=$Ticket Project=$Project Phase=$Phase"

# --- 2. Stage branding assets --------------------------------------------

$brandingDir = Join-Path $OutputDir 'sgfx_branding'
New-Item -ItemType Directory -Path $brandingDir -Force | Out-Null

$packIconRel = $null
if (Test-Path -LiteralPath $IconPath) {
    $iconExt = [System.IO.Path]::GetExtension($IconPath).ToLowerInvariant()
    if ($iconExt -ne '.png' -and $iconExt -ne '.bmp') {
        Add-Log "WARN: icon extension '$iconExt' is not .png/.bmp; SGBranding will skip it"
    }
    $iconDest = Join-Path $brandingDir ("icon" + $iconExt)
    Copy-Item -LiteralPath $IconPath -Destination $iconDest -Force
    $packIconRel = (Join-Path 'sgfx_branding' (Split-Path -Leaf $iconDest)) -replace '\\','/'
    Add-Log "icon copied: $IconPath -> $iconDest"
} else {
    Add-Log "WARN: IconPath not found, skipping: $IconPath"
}

if (Test-Path -LiteralPath $LogoPath) {
    $logoExt = [System.IO.Path]::GetExtension($LogoPath).ToLowerInvariant()
    $logoDest = Join-Path $brandingDir ("logo" + $logoExt)
    Copy-Item -LiteralPath $LogoPath -Destination $logoDest -Force
    Add-Log "logo copied: $LogoPath -> $logoDest"
} else {
    Add-Log "WARN: LogoPath not found, skipping: $LogoPath"
}

# --- 3. Stage scoped text rules ------------------------------------------

$textDir  = Join-Path $OutputDir 'text'
New-Item -ItemType Directory -Path $textDir -Force | Out-Null
$textPath = Join-Path $textDir 'sgfx_text.json'

# Build the text manifest as a literal templated string instead of
# round-tripping through ConvertTo-Json. PowerShell's JSON serializer
# wraps arrays stored under [ordered]@{} keys as
# `{ "value":[...], "Count":N }` due to PSObject decoration -- which
# breaks the v2 schema UR expects. Templating the rules in directly
# guarantees a clean JSON array regardless of how PowerShell models
# the in-memory representation.
$ruleJsonLines = New-Object System.Collections.Generic.List[string]
$ruleCount     = 0
$stringsBlob   = '{}'

if ($ScopedRulesJson -ne '') {
    if (-not (Test-Path -LiteralPath $ScopedRulesJson)) {
        throw "ScopedRulesJson not found: $ScopedRulesJson"
    }
    $rawText = Get-Content -LiteralPath $ScopedRulesJson -Raw
    $parsed = $rawText | ConvertFrom-Json
    $rulesIter = @()
    if ($parsed -is [System.Array]) {
        $rulesIter = @($parsed)
    } elseif ($parsed.scoped_rules) {
        $rulesIter = @($parsed.scoped_rules)
        if ($parsed.strings) {
            $stringsBlob = ($parsed.strings | ConvertTo-Json -Depth 8 -Compress)
        }
    } else {
        throw "ScopedRulesJson '$ScopedRulesJson' is neither an array nor a v2 object"
    }
    foreach ($rule in $rulesIter) {
        $ruleJsonLines.Add(($rule | ConvertTo-Json -Depth 6 -Compress))
        $ruleCount++
    }
    Add-Log "scoped rules sourced from $ScopedRulesJson (count=$ruleCount)"
} else {
    Add-Log "scoped rules: none (text manifest will be empty)"
}

$rulesEmbedded = ''
if ($ruleCount -gt 0) {
    $rulesEmbedded = "`n    " + (($ruleJsonLines.ToArray()) -join ",`n    ") + "`n  "
}
$textJson = @"
{
  "version": 2,
  "strings": $stringsBlob,
  "scoped_rules": [$rulesEmbedded]
}
"@
Set-Content -LiteralPath $textPath -Value $textJson -Encoding UTF8
Add-Log "wrote $textPath"

# --- 4. Stage pixel overrides --------------------------------------------

$picsDir  = Join-Path $OutputDir 'pictures'
New-Item -ItemType Directory -Path $picsDir -Force | Out-Null
$picsPath = Join-Path $picsDir 'sgfx_pictures.json'

$picsDoc = [ordered]@{
    version  = 1
    pictures = [ordered]@{}
}

if ($LogoSonicteamReplacement -and (Test-Path -LiteralPath $LogoSonicteamReplacement)) {
    $picCopy = Join-Path $picsDir 'logo_sonicteam_override.dds'
    Copy-Item -LiteralPath $LogoSonicteamReplacement -Destination $picCopy -Force
    $picsDoc.pictures['logo_sonicteam'] = 'pictures/logo_sonicteam_override.dds'
    Add-Log "logo_sonicteam override staged: $LogoSonicteamReplacement"
} else {
    Add-Log "logo_sonicteam override: none"
}

$picsJson = $picsDoc | ConvertTo-Json -Depth 6
Set-Content -LiteralPath $picsPath -Value $picsJson -Encoding UTF8
Add-Log "wrote $picsPath"

# --- 5. Stage loose-file substitutions -----------------------------------

$looseRelEntries = New-Object System.Collections.Generic.List[string]
if ($LooseFiles -and $LooseFiles.Count -gt 0) {
    $looseRoot = Join-Path $OutputDir 'loose'
    New-Item -ItemType Directory -Path $looseRoot -Force | Out-Null
    foreach ($entry in $LooseFiles) {
        $guest = $null; $source = $null
        if ($entry -is [hashtable]) {
            $guest  = [string]$entry['Guest']
            $source = [string]$entry['Source']
        } elseif ($entry.Guest -and $entry.Source) {
            $guest  = [string]$entry.Guest
            $source = [string]$entry.Source
        }
        if (-not $guest -or -not $source) {
            Add-Log "WARN: skipping malformed LooseFile entry"
            continue
        }
        if (-not (Test-Path -LiteralPath $source)) {
            Add-Log "WARN: loose source missing, skipping: $source"
            continue
        }
        $dstAbs = Resolve-PackChildPath -BaseDir $looseRoot -RelativePath $guest
        $dstParent = Split-Path -Parent $dstAbs
        if ($dstParent -and -not (Test-Path -LiteralPath $dstParent)) {
            New-Item -ItemType Directory -Path $dstParent -Force | Out-Null
        }
        Copy-Item -LiteralPath $source -Destination $dstAbs -Force
        $relForward = ("loose/" + ($guest -replace '\\','/'))
        $looseRelEntries.Add($relForward)
        Add-Log "loose: $source -> $relForward"
    }
}

# --- 6. Build sgfx_pack.json --------------------------------------------

$brandingNode = [ordered]@{
    window_title = $WindowTitle
    build_label  = $BuildLabel
}
if ($packIconRel) {
    $brandingNode['icon'] = $packIconRel
}

# Build sgfx_pack.json as a literal template (same reasoning as the
# text manifest above: round-tripping arrays through ConvertTo-Json
# under [ordered]@{} corrupts them with `value`/`Count` wrappers).
$brandingFields = @(
    ('"window_title": ' + ($WindowTitle | ConvertTo-Json -Compress)),
    ('"build_label": '  + ($BuildLabel  | ConvertTo-Json -Compress))
)
if ($packIconRel) {
    $brandingFields += ('"icon": ' + ($packIconRel | ConvertTo-Json -Compress))
}
$brandingJson = "{`n    " + ($brandingFields -join ",`n    ") + "`n  }"

$looseFilesJson = ''
if ($looseRelEntries.Count -gt 0) {
    $looseStrJsons = $looseRelEntries | ForEach-Object { $_ | ConvertTo-Json -Compress }
    $looseFilesJson = ",`n  `"loose_files`": [`n    " + (($looseStrJsons) -join ",`n    ") + "`n  ]"
}

$packPath = Join-Path $OutputDir 'sgfx_pack.json'
$packJson = @"
{
  "version": 1,
  "name": $($PackName | ConvertTo-Json -Compress),
  "description": $($PackDescription | ConvertTo-Json -Compress),
  "branding": $brandingJson,
  "text_overrides": "text/sgfx_text.json",
  "asset_overrides": "pictures/sgfx_pictures.json"$looseFilesJson
}
"@
Set-Content -LiteralPath $packPath -Value $packJson -Encoding UTF8
Add-Log "wrote $packPath"

# --- 7. Build pack_meta.json --------------------------------------------

$metaDoc = [ordered]@{
    version     = 1
    ticket      = $Ticket
    project     = $Project
    phase       = $Phase
    exporter    = 'sgfx_pack_exporter.ps1'
    exported_at = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
}
$metaPath = Join-Path $OutputDir 'pack_meta.json'
$metaJson = $metaDoc | ConvertTo-Json -Depth 4
Set-Content -LiteralPath $metaPath -Value $metaJson -Encoding UTF8
Add-Log "wrote $metaPath"

# --- 8. Persist pack_export.log -----------------------------------------

$logPath = Join-Path $OutputDir 'pack_export.log'
Set-Content -LiteralPath $logPath -Value ($logLines -join [System.Environment]::NewLine) -Encoding UTF8

Write-Host ""
Write-Host "SGFX pack exported to: $OutputDir" -ForegroundColor Green
$picCount = ($picsDoc.pictures.Keys | Measure-Object).Count
Write-Host "  ticket:  $Ticket"
Write-Host "  project: $Project"
Write-Host "  phase:   $Phase"
Write-Host "  rules:   $ruleCount scoped"
Write-Host "  pics:    $picCount entries"
Write-Host "  loose:   $($looseRelEntries.Count) entries"

# Emit the OutputDir so callers can pipe / capture it.
$OutputDir
