#pragma once

#include <array>
#include <string_view>

namespace sward::ui_runtime
{
struct DebugWorkbenchHostEntry
{
    std::string_view groupId;
    std::string_view groupDisplayName;
    std::string_view priority;
    std::string_view relativeSourcePath;
    std::string_view hostDisplayName;
    std::string_view primaryContractFileName;
    std::string_view aliasBlob;
    std::string_view notes;
};

inline constexpr std::array<DebugWorkbenchHostEntry, 133> kDebugWorkbenchHostEntries{{
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/Application.cpp",
        "Application.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/Application.cpp|Application.cpp|application_world_shell_reference.json|application_world_shell_reference|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/ApplicationDocument.cpp",
        "ApplicationDocument.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/ApplicationDocument.cpp|ApplicationDocument.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/ApplicationSetting.cpp",
        "ApplicationSetting.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/ApplicationSetting.cpp|ApplicationSetting.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/AutoDraw/AutoDrawManager.cpp",
        "AutoDrawManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/AutoDraw/AutoDrawManager.cpp|AutoDrawManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/CullingSystem/CullingElementSet.cpp",
        "CullingElementSet.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/CullingSystem/CullingElementSet.cpp|CullingElementSet.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Loader/DatabaseTree.cpp",
        "DatabaseTree.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|GameMode / Frontend Shell|frontend_gamemode_shell|System/GameMode/Loader/DatabaseTree.cpp|DatabaseTree.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/DynamicLoad.cpp",
        "DynamicLoad.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/DynamicLoad.cpp|DynamicLoad.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/DynamicLoadGITexture.cpp",
        "DynamicLoadGITexture.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/DynamicLoadGITexture.cpp|DynamicLoadGITexture.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/DynamicLoadTerrain.cpp",
        "DynamicLoadTerrain.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/DynamicLoadTerrain.cpp|DynamicLoadTerrain.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Ending/EndingImageList.cpp",
        "EndingImageList.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|System/GameMode/Ending/EndingImageList.cpp|EndingImageList.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Ending/EndingManager.cpp",
        "EndingManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|System/GameMode/Ending/EndingManager.cpp|EndingManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Ending/EndingText.cpp",
        "EndingText.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|System/GameMode/Ending/EndingText.cpp|EndingText.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/FlagManager.cpp",
        "FlagManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/FlagManager.cpp|FlagManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/Game.cpp",
        "Game.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/Game.cpp|Game.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameDocument.cpp",
        "GameDocument.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameDocument.cpp|GameDocument.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeBoot.cpp",
        "GameModeBoot.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Loading / Boot / Install|loading_and_boot|System/GameMode/GameModeBoot.cpp|GameModeBoot.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeEnding.cpp",
        "GameModeEnding.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|System/GameMode/GameModeEnding.cpp|GameModeEnding.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeMainMenu.cpp",
        "GameModeMainMenu.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/GameModeMainMenu.cpp|GameModeMainMenu.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeStage.cpp",
        "GameModeStage.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|GameMode / Frontend Shell|frontend_gamemode_shell|System/GameMode/GameModeStage.cpp|GameModeStage.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeStageInstall.cpp",
        "GameModeStageInstall.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Loading / Boot / Install|loading_and_boot|System/GameMode/GameModeStageInstall.cpp|GameModeStageInstall.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeStageLogo.cpp",
        "GameModeStageLogo.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Loading / Boot / Install|loading_and_boot|System/GameMode/GameModeStageLogo.cpp|GameModeStageLogo.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeStageMainMenu.cpp",
        "GameModeStageMainMenu.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/GameModeStageMainMenu.cpp|GameModeStageMainMenu.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeStageTitle.cpp",
        "GameModeStageTitle.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/GameModeStageTitle.cpp|GameModeStageTitle.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/GameModeTitleSelect.cpp",
        "GameModeTitleSelect.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/GameModeTitleSelect.cpp|GameModeTitleSelect.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObject.cpp",
        "GameObject.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObject.cpp|GameObject.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObject3D.cpp",
        "GameObject3D.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObject3D.cpp|GameObject3D.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObjectModel.cpp",
        "GameObjectModel.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObjectModel.cpp|GameObjectModel.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObjectRigidBody.cpp",
        "GameObjectRigidBody.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObjectRigidBody.cpp|GameObjectRigidBody.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObjectSky.cpp",
        "GameObjectSky.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObjectSky.cpp|GameObjectSky.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameObjectTerrain.cpp",
        "GameObjectTerrain.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameObjectTerrain.cpp|GameObjectTerrain.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameParameter.cpp",
        "GameParameter.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/GameParameter.cpp|GameParameter.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "HUD/StageSelect/HudStageSelect.cpp",
        "HudStageSelect.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|HUD/StageSelect/HudStageSelect.cpp|HudStageSelect.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "HUD/Install/InstallDisplay.cpp",
        "InstallDisplay.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Loading / Boot / Install|loading_and_boot|HUD/Install/InstallDisplay.cpp|InstallDisplay.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/LightManager/LightManager.cpp",
        "LightManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/LightManager/LightManager.cpp|LightManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "HUD/Loading/Loading.cpp",
        "Loading.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Loading / Boot / Install|loading_and_boot|HUD/Loading/Loading.cpp|Loading.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/LightManager/LocalLight.cpp",
        "LocalLight.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/LightManager/LocalLight.cpp|LocalLight.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/MainMenu/MainMenuManager.cpp",
        "MainMenuManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/MainMenu/MainMenuManager.cpp|MainMenuManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/NextStagePreloadingManager.cpp",
        "NextStagePreloadingManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/NextStagePreloadingManager.cpp|NextStagePreloadingManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/PvsManager.cpp",
        "PvsManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/PvsManager.cpp|PvsManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/RenderDirector/RenderDirectorFxPipeline.cpp",
        "RenderDirectorFxPipeline.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/RenderDirector/RenderDirectorFxPipeline.cpp|RenderDirectorFxPipeline.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/RenderDirector/RenderDirectorSceneEffect.cpp",
        "RenderDirectorSceneEffect.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/RenderDirector/RenderDirectorSceneEffect.cpp|RenderDirectorSceneEffect.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/SaveLoadTest.cpp",
        "SaveLoadTest.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|System/SaveLoadTest.cpp|SaveLoadTest.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "Sequence/Unit/SequenceUnitAutoSave.cpp",
        "SequenceUnitAutoSave.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|Sequence/Unit/SequenceUnitAutoSave.cpp|SequenceUnitAutoSave.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "Sequence/Unit/SequenceUnitRegisterClearFlag.cpp",
        "SequenceUnitRegisterClearFlag.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Save / Ending Flow|save_and_ending|Sequence/Unit/SequenceUnitRegisterClearFlag.cpp|SequenceUnitRegisterClearFlag.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/StageListManager.cpp",
        "StageListManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/StageListManager.cpp|StageListManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Loader/StageLoaderXML.cpp",
        "StageLoaderXML.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|GameMode / Frontend Shell|frontend_gamemode_shell|System/GameMode/Loader/StageLoaderXML.cpp|StageLoaderXML.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/StageManager.cpp",
        "StageManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/StageManager.cpp|StageManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/TerrainManager.cpp",
        "TerrainManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/TerrainManager.cpp|TerrainManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/TerrainManager2nd.cpp",
        "TerrainManager2nd.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/TerrainManager2nd.cpp|TerrainManager2nd.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Title/TitleManager.cpp",
        "TitleManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/Title/TitleManager.cpp|TitleManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Title/TitleMenu.cpp",
        "TitleMenu.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/Title/TitleMenu.cpp|TitleMenu.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Title/TitleStateIntro.cpp",
        "TitleStateIntro.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Title / Main Menu|title_menu|System/GameMode/Title/TitleStateIntro.cpp|TitleStateIntro.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/Title/TitleStateWorldMap.cpp",
        "TitleStateWorldMap.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/Title/TitleStateWorldMap.cpp|TitleStateWorldMap.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/Vibration.cpp",
        "Vibration.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/Vibration.cpp|Vibration.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/CullingSystem/VisibilityCullingManager.cpp",
        "VisibilityCullingManager.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/CullingSystem/VisibilityCullingManager.cpp|VisibilityCullingManager.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/CullingSystem/VisibilityCullingStrategy.cpp",
        "VisibilityCullingStrategy.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/CullingSystem/VisibilityCullingStrategy.cpp|VisibilityCullingStrategy.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/VoiceComponent.cpp",
        "VoiceComponent.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/VoiceComponent.cpp|VoiceComponent.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/World.cpp",
        "World.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|Frontend System Shell|frontend_system_shell|System/World.cpp|World.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapListBox.cpp",
        "WorldMapListBox.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapListBox.cpp|WorldMapListBox.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapMission.cpp",
        "WorldMapMission.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapMission.cpp|WorldMapMission.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapObject.cpp",
        "WorldMapObject.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapObject.cpp|WorldMapObject.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapSelect.cpp",
        "WorldMapSelect.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapSelect.cpp|WorldMapSelect.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapSimpleInfo.cpp",
        "WorldMapSimpleInfo.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapSimpleInfo.cpp|WorldMapSimpleInfo.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "application_world_shell_hosts",
        "Application / World Shell Hosts",
        "high",
        "System/GameMode/WorldMap/WorldMapTutorial.cpp",
        "WorldMapTutorial.cpp",
        "application_world_shell_reference.json",
        "Application / World Shell Hosts|application_world_shell_hosts|Application / World Shell|application_world_shell|World Map Stack|world_map_stack|System/GameMode/WorldMap/WorldMapTutorial.cpp|WorldMapTutorial.cpp|application_world_shell_reference.json|application_world_shell_reference|Application.cpp|GameModeBoot.cpp|TitleMenu.cpp|WorldMapSelect.cpp",
        "Application, document, gamemode, title, and world-shell ownership tied to the portable app/world contract.",
    },
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossHudSuperSonic.cpp",
        "BossHudSuperSonic.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossHudSuperSonic.cpp|BossHudSuperSonic.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossHudVitality.cpp",
        "BossHudVitality.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossHudVitality.cpp|BossHudVitality.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossNamePlate.cpp",
        "BossNamePlate.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossNamePlate.cpp|BossNamePlate.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "camera_replay_hosts",
        "Camera / Replay Hosts",
        "medium",
        "Camera/Controller/FreeCamera.cpp",
        "FreeCamera.cpp",
        "camera_shell_reference.json",
        "Camera / Replay Hosts|camera_replay_hosts|Camera / Replay Shell|camera_shell|Tooling / Debug UI|tooling_debug_ui|Camera/Controller/FreeCamera.cpp|FreeCamera.cpp|camera_shell_reference.json|camera_shell_reference|ReplayFreeCamera.cpp|GoalCamera.cpp",
        "Free, replay, goal, and town-support camera hosts driven through the camera/replay shell contract.",
    },
    {
        "camera_replay_hosts",
        "Camera / Replay Hosts",
        "medium",
        "Camera/Controller/GoalCamera.cpp",
        "GoalCamera.cpp",
        "camera_shell_reference.json",
        "Camera / Replay Hosts|camera_replay_hosts|Camera / Replay Shell|camera_shell|Frontend Camera Shell|frontend_camera_shell|Camera/Controller/GoalCamera.cpp|GoalCamera.cpp|camera_shell_reference.json|camera_shell_reference|FreeCamera.cpp|ReplayFreeCamera.cpp",
        "Free, replay, goal, and town-support camera hosts driven through the camera/replay shell contract.",
    },
    {
        "camera_replay_hosts",
        "Camera / Replay Hosts",
        "medium",
        "Replay/Camera/ReplayFreeCamera.cpp",
        "ReplayFreeCamera.cpp",
        "camera_shell_reference.json",
        "Camera / Replay Hosts|camera_replay_hosts|Camera / Replay Shell|camera_shell|Tooling / Debug UI|tooling_debug_ui|Replay/Camera/ReplayFreeCamera.cpp|ReplayFreeCamera.cpp|camera_shell_reference.json|camera_shell_reference|FreeCamera.cpp|GoalCamera.cpp",
        "Free, replay, goal, and town-support camera hosts driven through the camera/replay shell contract.",
    },
    {
        "camera_replay_hosts",
        "Camera / Replay Hosts",
        "medium",
        "Replay/Camera/ReplayRelativeCamera.cpp",
        "ReplayRelativeCamera.cpp",
        "camera_shell_reference.json",
        "Camera / Replay Hosts|camera_replay_hosts|Camera / Replay Shell|camera_shell|Tooling / Debug UI|tooling_debug_ui|Replay/Camera/ReplayRelativeCamera.cpp|ReplayRelativeCamera.cpp|camera_shell_reference.json|camera_shell_reference|FreeCamera.cpp|ReplayFreeCamera.cpp|GoalCamera.cpp",
        "Free, replay, goal, and town-support camera hosts driven through the camera/replay shell contract.",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "System/GameMode/GameModeStageMovie.cpp",
        "GameModeStageMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|System/GameMode/GameModeStageMovie.cpp|GameModeStageMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspireObject.cpp",
        "InspireObject.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspireObject.cpp|InspireObject.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreview.cpp",
        "InspirePreview.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreview.cpp|InspirePreview.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2nd.cpp",
        "InspirePreview2nd.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2nd.cpp|InspirePreview2nd.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp",
        "InspirePreview2ndMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp|InspirePreview2ndMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreviewMenu.cpp",
        "InspirePreviewMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreviewMenu.cpp|InspirePreviewMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraMenu.cpp",
        "MotionCameraMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraMenu.cpp|MotionCameraMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraTool.cpp",
        "MotionCameraTool.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraTool.cpp|MotionCameraTool.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Movie/MovieManager.cpp",
        "MovieManager.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Movie/MovieManager.cpp|MovieManager.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Utility/SequencePlayMovieWrapper.cpp",
        "SequencePlayMovieWrapper.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Utility/SequencePlayMovieWrapper.cpp|SequencePlayMovieWrapper.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitMicroSequence.cpp",
        "SequenceUnitMicroSequence.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitMicroSequence.cpp|SequenceUnitMicroSequence.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitPlayMovie.cpp",
        "SequenceUnitPlayMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitPlayMovie.cpp|SequenceUnitPlayMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "frontend_sequence_hosts",
        "Frontend Sequence Hosts",
        "high",
        "Sequence/Core/SequenceHandleUnit.cpp",
        "SequenceHandleUnit.cpp",
        "frontend_sequence_shell_reference.json",
        "Frontend Sequence Hosts|frontend_sequence_hosts|Frontend Sequence Shell|frontend_sequence_shell|Sequence/Core/SequenceHandleUnit.cpp|SequenceHandleUnit.cpp|frontend_sequence_shell_reference.json|frontend_sequence_shell_reference|SequenceManagerImpl.cpp|SequenceUnitFactory.cpp",
        "Sequence-core and unit-factory hosts driven through the recovered frontend sequence shell contract.",
    },
    {
        "frontend_sequence_hosts",
        "Frontend Sequence Hosts",
        "high",
        "Sequence/Core/SequenceManagerImpl.cpp",
        "SequenceManagerImpl.cpp",
        "frontend_sequence_shell_reference.json",
        "Frontend Sequence Hosts|frontend_sequence_hosts|Frontend Sequence Shell|frontend_sequence_shell|Sequence/Core/SequenceManagerImpl.cpp|SequenceManagerImpl.cpp|frontend_sequence_shell_reference.json|frontend_sequence_shell_reference|SequenceHandleUnit.cpp|SequenceUnitFactory.cpp",
        "Sequence-core and unit-factory hosts driven through the recovered frontend sequence shell contract.",
    },
    {
        "frontend_sequence_hosts",
        "Frontend Sequence Hosts",
        "high",
        "Sequence/Unit/SequenceUnitFactory.cpp",
        "SequenceUnitFactory.cpp",
        "frontend_sequence_shell_reference.json",
        "Frontend Sequence Hosts|frontend_sequence_hosts|Frontend Sequence Shell|frontend_sequence_shell|Sequence/Unit/SequenceUnitFactory.cpp|SequenceUnitFactory.cpp|frontend_sequence_shell_reference.json|frontend_sequence_shell_reference|SequenceManagerImpl.cpp|SequenceHandleUnit.cpp",
        "Sequence-core and unit-factory hosts driven through the recovered frontend sequence shell contract.",
    },
    {
        "frontend_sequence_hosts",
        "Frontend Sequence Hosts",
        "high",
        "Sequence/Unit/SequenceUnitUnlockAchievement.cpp",
        "SequenceUnitUnlockAchievement.cpp",
        "frontend_sequence_shell_reference.json",
        "Frontend Sequence Hosts|frontend_sequence_hosts|Frontend Sequence Shell|frontend_sequence_shell|Sequence/Unit/SequenceUnitUnlockAchievement.cpp|SequenceUnitUnlockAchievement.cpp|frontend_sequence_shell_reference.json|frontend_sequence_shell_reference|SequenceManagerImpl.cpp|SequenceHandleUnit.cpp|SequenceUnitFactory.cpp",
        "Sequence-core and unit-factory hosts driven through the recovered frontend sequence shell contract.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/EvilSonic/Hud/EvilHudGuide.cpp",
        "EvilHudGuide.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|Player/Character/EvilSonic/Hud/EvilHudGuide.cpp|EvilHudGuide.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/EvilSonic/Hud/EvilHudTarget.cpp",
        "EvilHudTarget.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|Player/Character/EvilSonic/Hud/EvilHudTarget.cpp|EvilHudTarget.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Evil/EvilMainDisplay.cpp",
        "EvilMainDisplay.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|HUD/Evil/EvilMainDisplay.cpp|EvilMainDisplay.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Evil/HudEvilStage.cpp",
        "HudEvilStage.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|HUD/Evil/HudEvilStage.cpp|HudEvilStage.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "ExtraStage/Tails/Hud/HudExQte.cpp",
        "HudExQte.cpp",
        "extra_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Extra Stage / Tornado Defense HUD|extra_stage_hud|ExtraStage/Tails/Hud/HudExQte.cpp|HudExQte.cpp|extra_stage_hud_reference.json|extra_stage_hud_reference|ui_prov_playscreen|ui_qte|GameModeStageMotionTest.cpp",
        "Extra-stage / Tornado Defense HUD ownership with counter shells and QTE prompt layers.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Sonic/HudSonicStage.cpp",
        "HudSonicStage.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|HUD/Sonic/HudSonicStage.cpp|HudSonicStage.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/Sonic/Hud/SonicHudGuide.cpp",
        "SonicHudGuide.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|Player/Character/Sonic/Hud/SonicHudGuide.cpp|SonicHudGuide.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/Sonic/Hud/SonicHudHomingAttack.cpp",
        "SonicHudHomingAttack.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|Player/Character/Sonic/Hud/SonicHudHomingAttack.cpp|SonicHudHomingAttack.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Sonic/SonicMainDisplay.cpp",
        "SonicMainDisplay.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|HUD/Sonic/SonicMainDisplay.cpp|SonicMainDisplay.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMainMenu_Test.cpp",
        "GameModeMainMenu_Test.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMainMenu_Test.cpp|GameModeMainMenu_Test.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMenuSelectDebug.cpp",
        "GameModeMenuSelectDebug.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMenuSelectDebug.cpp|GameModeMenuSelectDebug.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeStageSelectDebug.cpp",
        "GameModeStageSelectDebug.cpp",
        "loading_transition_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSelectDebug.cpp|GameModeStageSelectDebug.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Utility/SequenceChangeStageUnit.cpp",
        "SequenceChangeStageUnit.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Utility/SequenceChangeStageUnit.cpp|SequenceChangeStageUnit.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitCallHelpWindow.cpp",
        "SequenceUnitCallHelpWindow.cpp",
        "pause_menu_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Pause Stack|pause_stack|Sequence/Unit/SequenceUnitCallHelpWindow.cpp|SequenceUnitCallHelpWindow.cpp|pause_menu_reference.json|pause_menu_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitChangeStage.cpp",
        "SequenceUnitChangeStage.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitChangeStage.cpp|SequenceUnitChangeStage.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitSwapDisk.cpp",
        "SequenceUnitSwapDisk.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitSwapDisk.cpp|SequenceUnitSwapDisk.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageAchievementTest.cpp",
        "GameModeStageAchievementTest.cpp",
        "boss_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageAchievementTest.cpp|GameModeStageAchievementTest.cpp|boss_hud_reference.json|boss_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageEvilTest.cpp",
        "GameModeStageEvilTest.cpp",
        "werehog_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageEvilTest.cpp|GameModeStageEvilTest.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageForwardTest.cpp",
        "GameModeStageForwardTest.cpp",
        "sonic_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageForwardTest.cpp|GameModeStageForwardTest.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageInstallTest.cpp",
        "GameModeStageInstallTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageInstallTest.cpp|GameModeStageInstallTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageLoadXML.cpp",
        "GameModeStageLoadXML.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageLoadXML.cpp|GameModeStageLoadXML.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageMotionTest.cpp",
        "GameModeStageMotionTest.cpp",
        "extra_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageMotionTest.cpp|GameModeStageMotionTest.cpp|extra_stage_hud_reference.json|extra_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSaveTest.cpp",
        "GameModeStageSaveTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSaveTest.cpp|GameModeStageSaveTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageScreenshot.cpp",
        "GameModeStageScreenshot.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageScreenshot.cpp|GameModeStageScreenshot.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSwapDiskTest.cpp",
        "GameModeStageSwapDiskTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSwapDiskTest.cpp|GameModeStageSwapDiskTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/DialogScript.cpp",
        "DialogScript.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/DialogScript.cpp|DialogScript.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/HotdogParamManager.cpp",
        "HotdogParamManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/HotdogParamManager.cpp|HotdogParamManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/HotdogSaveManager.cpp",
        "HotdogSaveManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/HotdogSaveManager.cpp|HotdogSaveManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/ItemParamManager.cpp",
        "ItemParamManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/ItemParamManager.cpp|ItemParamManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/KyojuParamManager.cpp",
        "KyojuParamManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/KyojuParamManager.cpp|KyojuParamManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/KyojuPresentManager.cpp",
        "KyojuPresentManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/KyojuPresentManager.cpp|KyojuPresentManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "HUD/MediaRoom/MediaRoom.cpp",
        "MediaRoom.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|HUD/MediaRoom/MediaRoom.cpp|MediaRoom.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "HUD/MediaRoom/MediaRoomDetail.cpp",
        "MediaRoomDetail.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|HUD/MediaRoom/MediaRoomDetail.cpp|MediaRoomDetail.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "HUD/MediaRoom/MediaRoomItemList.cpp",
        "MediaRoomItemList.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|HUD/MediaRoom/MediaRoomItemList.cpp|MediaRoomItemList.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "HUD/MediaRoom/MediaRoomSelectCountry.cpp",
        "MediaRoomSelectCountry.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|HUD/MediaRoom/MediaRoomSelectCountry.cpp|MediaRoomSelectCountry.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "HUD/MediaRoom/MediaRoomSelectItem.cpp",
        "MediaRoomSelectItem.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|HUD/MediaRoom/MediaRoomSelectItem.cpp|MediaRoomSelectItem.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Sequence/Unit/SequenceUnitSendMediaRoomMessage.cpp",
        "SequenceUnitSendMediaRoomMessage.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Sequence/Unit/SequenceUnitSendMediaRoomMessage.cpp|SequenceUnitSendMediaRoomMessage.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Sequence/Unit/SequenceUnitSendTownMessage.cpp",
        "SequenceUnitSendTownMessage.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Sequence/Unit/SequenceUnitSendTownMessage.cpp|SequenceUnitSendTownMessage.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/ShopParamManager.cpp",
        "ShopParamManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/ShopParamManager.cpp|ShopParamManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/ShopWindow.cpp",
        "ShopWindow.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/ShopWindow.cpp|ShopWindow.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/SunafkinParamManager.cpp",
        "SunafkinParamManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/SunafkinParamManager.cpp|SunafkinParamManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/TalkWindow.cpp",
        "TalkWindow.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/TalkWindow.cpp|TalkWindow.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/TimeTableManager.cpp",
        "TimeTableManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/TimeTableManager.cpp|TimeTableManager.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Town/TownManager.cpp",
        "TownManager.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Town/TownManager.cpp|TownManager.cpp|town_ui_reference.json|town_ui_reference|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Camera/Controller/TownShopCamera.cpp",
        "TownShopCamera.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Camera/Controller/TownShopCamera.cpp|TownShopCamera.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
    {
        "town_media_room_hosts",
        "Town / Media Room Hosts",
        "high",
        "Camera/Controller/TownTalkCamera.cpp",
        "TownTalkCamera.cpp",
        "town_ui_reference.json",
        "Town / Media Room Hosts|town_media_room_hosts|Town UI|town_ui|Town / Media Room UI|Camera/Controller/TownTalkCamera.cpp|TownTalkCamera.cpp|town_ui_reference.json|town_ui_reference|TownManager.cpp|TalkWindow.cpp|ShopWindow.cpp|MediaRoom.cpp",
        "Town, shop, talk, and media-room ownership tied back to the town shell runtime contract.",
    },
}};
} // namespace sward::ui_runtime
