#pragma once

#include <array>
#include <string_view>

namespace sward::ui_runtime
{
struct DebugWorkbenchHostEntry
{
    std::string_view groupId;
    std::string_view groupDisplayName;
    std::string_view priority;
    std::string_view relativeSourcePath;
    std::string_view hostDisplayName;
    std::string_view primaryContractFileName;
    std::string_view aliasBlob;
    std::string_view notes;
};

inline constexpr std::array<DebugWorkbenchHostEntry, 28> kDebugWorkbenchHostEntries{{
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "System/GameMode/GameModeStageMovie.cpp",
        "GameModeStageMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|System/GameMode/GameModeStageMovie.cpp|GameModeStageMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspireObject.cpp",
        "InspireObject.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspireObject.cpp|InspireObject.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreview.cpp",
        "InspirePreview.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreview.cpp|InspirePreview.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2nd.cpp",
        "InspirePreview2nd.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2nd.cpp|InspirePreview2nd.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp",
        "InspirePreview2ndMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp|InspirePreview2ndMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreviewMenu.cpp",
        "InspirePreviewMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreviewMenu.cpp|InspirePreviewMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraMenu.cpp",
        "MotionCameraMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraMenu.cpp|MotionCameraMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraTool.cpp",
        "MotionCameraTool.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraTool.cpp|MotionCameraTool.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Movie/MovieManager.cpp",
        "MovieManager.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Movie/MovieManager.cpp|MovieManager.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Utility/SequencePlayMovieWrapper.cpp",
        "SequencePlayMovieWrapper.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Utility/SequencePlayMovieWrapper.cpp|SequencePlayMovieWrapper.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitMicroSequence.cpp",
        "SequenceUnitMicroSequence.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitMicroSequence.cpp|SequenceUnitMicroSequence.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitPlayMovie.cpp",
        "SequenceUnitPlayMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitPlayMovie.cpp|SequenceUnitPlayMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMainMenu_Test.cpp",
        "GameModeMainMenu_Test.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMainMenu_Test.cpp|GameModeMainMenu_Test.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMenuSelectDebug.cpp",
        "GameModeMenuSelectDebug.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMenuSelectDebug.cpp|GameModeMenuSelectDebug.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeStageSelectDebug.cpp",
        "GameModeStageSelectDebug.cpp",
        "loading_transition_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSelectDebug.cpp|GameModeStageSelectDebug.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Utility/SequenceChangeStageUnit.cpp",
        "SequenceChangeStageUnit.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Utility/SequenceChangeStageUnit.cpp|SequenceChangeStageUnit.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitCallHelpWindow.cpp",
        "SequenceUnitCallHelpWindow.cpp",
        "pause_menu_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Pause Stack|pause_stack|Sequence/Unit/SequenceUnitCallHelpWindow.cpp|SequenceUnitCallHelpWindow.cpp|pause_menu_reference.json|pause_menu_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitChangeStage.cpp",
        "SequenceUnitChangeStage.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitChangeStage.cpp|SequenceUnitChangeStage.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitSwapDisk.cpp",
        "SequenceUnitSwapDisk.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitSwapDisk.cpp|SequenceUnitSwapDisk.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageAchievementTest.cpp",
        "GameModeStageAchievementTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageAchievementTest.cpp|GameModeStageAchievementTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageEvilTest.cpp",
        "GameModeStageEvilTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageEvilTest.cpp|GameModeStageEvilTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageForwardTest.cpp",
        "GameModeStageForwardTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageForwardTest.cpp|GameModeStageForwardTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageInstallTest.cpp",
        "GameModeStageInstallTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageInstallTest.cpp|GameModeStageInstallTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageLoadXML.cpp",
        "GameModeStageLoadXML.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageLoadXML.cpp|GameModeStageLoadXML.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageMotionTest.cpp",
        "GameModeStageMotionTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageMotionTest.cpp|GameModeStageMotionTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSaveTest.cpp",
        "GameModeStageSaveTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSaveTest.cpp|GameModeStageSaveTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageScreenshot.cpp",
        "GameModeStageScreenshot.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageScreenshot.cpp|GameModeStageScreenshot.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSwapDiskTest.cpp",
        "GameModeStageSwapDiskTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSwapDiskTest.cpp|GameModeStageSwapDiskTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
}};
} // namespace sward::ui_runtime
