#pragma once

#include <array>
#include <string_view>

namespace sward::ui_runtime
{
struct DebugWorkbenchHostEntry
{
    std::string_view groupId;
    std::string_view groupDisplayName;
    std::string_view priority;
    std::string_view relativeSourcePath;
    std::string_view hostDisplayName;
    std::string_view primaryContractFileName;
    std::string_view aliasBlob;
    std::string_view notes;
};

inline constexpr std::array<DebugWorkbenchHostEntry, 40> kDebugWorkbenchHostEntries{{
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossHudSuperSonic.cpp",
        "BossHudSuperSonic.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossHudSuperSonic.cpp|BossHudSuperSonic.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossHudVitality.cpp",
        "BossHudVitality.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossHudVitality.cpp|BossHudVitality.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "boss_hud_hosts",
        "Boss / Final HUD Hosts",
        "high",
        "Boss/BossNamePlate.cpp",
        "BossNamePlate.cpp",
        "super_sonic_hud_reference.json",
        "Boss / Final HUD Hosts|boss_hud_hosts|Super Sonic / Final HUD Bridge|super_sonic_hud|Boss/BossNamePlate.cpp|BossNamePlate.cpp|super_sonic_hud_reference.json|super_sonic_hud_reference|ui_playscreen_su",
        "Super Sonic and final-phase HUD bridge with shared vitality and nameplate ownership.",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "System/GameMode/GameModeStageMovie.cpp",
        "GameModeStageMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|System/GameMode/GameModeStageMovie.cpp|GameModeStageMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspireObject.cpp",
        "InspireObject.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspireObject.cpp|InspireObject.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreview.cpp",
        "InspirePreview.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreview.cpp|InspirePreview.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2nd.cpp",
        "InspirePreview2nd.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2nd.cpp|InspirePreview2nd.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp",
        "InspirePreview2ndMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview2nd/InspirePreview2ndMenu.cpp|InspirePreview2ndMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/InspirePreview/InspirePreviewMenu.cpp",
        "InspirePreviewMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/InspirePreview/InspirePreviewMenu.cpp|InspirePreviewMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraMenu.cpp",
        "MotionCameraMenu.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraMenu.cpp|MotionCameraMenu.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Tool/MotionCameraTool/MotionCameraTool.cpp",
        "MotionCameraTool.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Tooling / Debug UI|tooling_debug_ui|Tool/MotionCameraTool/MotionCameraTool.cpp|MotionCameraTool.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Movie/MovieManager.cpp",
        "MovieManager.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Movie/MovieManager.cpp|MovieManager.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Utility/SequencePlayMovieWrapper.cpp",
        "SequencePlayMovieWrapper.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Utility/SequencePlayMovieWrapper.cpp|SequencePlayMovieWrapper.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitMicroSequence.cpp",
        "SequenceUnitMicroSequence.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitMicroSequence.cpp|SequenceUnitMicroSequence.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "cutscene_preview_hosts",
        "Cutscene / Preview Hosts",
        "immediate",
        "Sequence/Unit/SequenceUnitPlayMovie.cpp",
        "SequenceUnitPlayMovie.cpp",
        "subtitle_cutscene_reference.json",
        "Cutscene / Preview Hosts|cutscene_preview_hosts|Subtitle / Cutscene Presentation|subtitle_cutscene|Sequence/Unit/SequenceUnitPlayMovie.cpp|SequenceUnitPlayMovie.cpp|subtitle_cutscene_reference.json|subtitle_cutscene_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/EvilSonic/Hud/EvilHudGuide.cpp",
        "EvilHudGuide.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|Player/Character/EvilSonic/Hud/EvilHudGuide.cpp|EvilHudGuide.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/EvilSonic/Hud/EvilHudTarget.cpp",
        "EvilHudTarget.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|Player/Character/EvilSonic/Hud/EvilHudTarget.cpp|EvilHudTarget.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Evil/EvilMainDisplay.cpp",
        "EvilMainDisplay.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|HUD/Evil/EvilMainDisplay.cpp|EvilMainDisplay.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Evil/HudEvilStage.cpp",
        "HudEvilStage.cpp",
        "werehog_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Werehog Stage HUD|werehog_stage_hud|HUD/Evil/HudEvilStage.cpp|HudEvilStage.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference|ui_playscreen_ev|ui_playscreen_ev_hit|GameModeStageEvilTest.cpp",
        "Werehog-stage HUD ownership with life/unleash/shield gauges and hit-counter overlays.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "ExtraStage/Tails/Hud/HudExQte.cpp",
        "HudExQte.cpp",
        "extra_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Extra Stage / Tornado Defense HUD|extra_stage_hud|ExtraStage/Tails/Hud/HudExQte.cpp|HudExQte.cpp|extra_stage_hud_reference.json|extra_stage_hud_reference|ui_prov_playscreen|ui_qte|GameModeStageMotionTest.cpp",
        "Extra-stage / Tornado Defense HUD ownership with counter shells and QTE prompt layers.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Sonic/HudSonicStage.cpp",
        "HudSonicStage.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|HUD/Sonic/HudSonicStage.cpp|HudSonicStage.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/Sonic/Hud/SonicHudGuide.cpp",
        "SonicHudGuide.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|Player/Character/Sonic/Hud/SonicHudGuide.cpp|SonicHudGuide.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "Player/Character/Sonic/Hud/SonicHudHomingAttack.cpp",
        "SonicHudHomingAttack.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|Player/Character/Sonic/Hud/SonicHudHomingAttack.cpp|SonicHudHomingAttack.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "gameplay_hud_hosts",
        "Gameplay HUD Hosts",
        "high",
        "HUD/Sonic/SonicMainDisplay.cpp",
        "SonicMainDisplay.cpp",
        "sonic_stage_hud_reference.json",
        "Gameplay HUD Hosts|gameplay_hud_hosts|Sonic Stage HUD|sonic_stage_hud|HUD/Sonic/SonicMainDisplay.cpp|SonicMainDisplay.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference|ui_playscreen|GameModeStageForwardTest.cpp",
        "Day-stage HUD ownership with counters, medal sidecars, and boost/ring gauge shells.",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMainMenu_Test.cpp",
        "GameModeMainMenu_Test.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMainMenu_Test.cpp|GameModeMainMenu_Test.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeMenuSelectDebug.cpp",
        "GameModeMenuSelectDebug.cpp",
        "title_menu_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeMenuSelectDebug.cpp|GameModeMenuSelectDebug.cpp|title_menu_reference.json|title_menu_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "menu_debug_hosts",
        "Menu / Stage Debug Hosts",
        "immediate",
        "System/GameMode/GameModeStageSelectDebug.cpp",
        "GameModeStageSelectDebug.cpp",
        "loading_transition_reference.json",
        "Menu / Stage Debug Hosts|menu_debug_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSelectDebug.cpp|GameModeStageSelectDebug.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Utility/SequenceChangeStageUnit.cpp",
        "SequenceChangeStageUnit.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Utility/SequenceChangeStageUnit.cpp|SequenceChangeStageUnit.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitCallHelpWindow.cpp",
        "SequenceUnitCallHelpWindow.cpp",
        "pause_menu_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Pause Stack|pause_stack|Sequence/Unit/SequenceUnitCallHelpWindow.cpp|SequenceUnitCallHelpWindow.cpp|pause_menu_reference.json|pause_menu_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitChangeStage.cpp",
        "SequenceUnitChangeStage.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitChangeStage.cpp|SequenceUnitChangeStage.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "pause_help_and_loading_dispatch",
        "Pause / Help / Loading Dispatch",
        "high",
        "Sequence/Unit/SequenceUnitSwapDisk.cpp",
        "SequenceUnitSwapDisk.cpp",
        "loading_transition_reference.json",
        "Pause / Help / Loading Dispatch|pause_help_and_loading_dispatch|Loading / Boot / Install|loading_and_boot|Sequence/Unit/SequenceUnitSwapDisk.cpp|SequenceUnitSwapDisk.cpp|loading_transition_reference.json|loading_transition_reference",
        "lift current contract/runtime examples into source-path-named debug screens",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageAchievementTest.cpp",
        "GameModeStageAchievementTest.cpp",
        "boss_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageAchievementTest.cpp|GameModeStageAchievementTest.cpp|boss_hud_reference.json|boss_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageEvilTest.cpp",
        "GameModeStageEvilTest.cpp",
        "werehog_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageEvilTest.cpp|GameModeStageEvilTest.cpp|werehog_stage_hud_reference.json|werehog_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageForwardTest.cpp",
        "GameModeStageForwardTest.cpp",
        "sonic_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageForwardTest.cpp|GameModeStageForwardTest.cpp|sonic_stage_hud_reference.json|sonic_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageInstallTest.cpp",
        "GameModeStageInstallTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageInstallTest.cpp|GameModeStageInstallTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageLoadXML.cpp",
        "GameModeStageLoadXML.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageLoadXML.cpp|GameModeStageLoadXML.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageMotionTest.cpp",
        "GameModeStageMotionTest.cpp",
        "extra_stage_hud_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageMotionTest.cpp|GameModeStageMotionTest.cpp|extra_stage_hud_reference.json|extra_stage_hud_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSaveTest.cpp",
        "GameModeStageSaveTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSaveTest.cpp|GameModeStageSaveTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageScreenshot.cpp",
        "GameModeStageScreenshot.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageScreenshot.cpp|GameModeStageScreenshot.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
    {
        "stage_test_hosts",
        "Stage Test / Validation Hosts",
        "high",
        "System/GameMode/GameModeStageSwapDiskTest.cpp",
        "GameModeStageSwapDiskTest.cpp",
        "loading_transition_reference.json",
        "Stage Test / Validation Hosts|stage_test_hosts|Tooling / Debug UI|tooling_debug_ui|System/GameMode/GameModeStageSwapDiskTest.cpp|GameModeStageSwapDiskTest.cpp|loading_transition_reference.json|loading_transition_reference",
        "use this as a host surface for the future UI capability sandbox",
    },
}};
} // namespace sward::ui_runtime
