#!/usr/bin/env python3
"""
extract_ui_assets.py — turn YOUR own Sonic Unleashed copy into the
PNGs + manifests the SWARD viewer auto-loads.

This tool ships NO game assets. It reads the archives from YOUR
installed/dumped copy (the same copy UnleashedRecomp requires), unpacks
them, converts the DDS textures to PNG, and emits one manifest per
screen so the viewer composes each screen 1:1 from your files — with no
manual placement.

Pipeline per screen:
  1. unpack the relevant .ar/.arl archive   (HedgeArcPack)
  2. parse the .yncp layout                 (your research_uiux parser)
  3. for each cast node: record rect (1280x720 ref space) + texture id
  4. convert that node's DDS subimage -> PNG (texconv on Windows, or
     Pillow if you already have loose PNG/DDS)
  5. write  <out>/assets/<screen>/*.png  and  <out>/manifests/<screen>.json

Dependencies (all things you already have in this repo / can pip install):
  - external_tools/HedgeArcPack  (already in your tree)
  - python -m pip install pillow
  - (Windows, for BC/DXT DDS) Microsoft 'texconv.exe' on PATH
  - your existing .yncp parser under research_uiux/tools

Usage:
  python tools/extract_ui_assets.py \
      --game "Unleashed Recomp - Windows (Complete Installation) 1.0.3/game" \
      --out  .                                   \
      --screens title sonic_hud pause world_map

Only the manifest WRITER + DDS->PNG steps are here in full; the .yncp
node-rect reader calls into your repo's parser (import path configurable
with --parser). If that parser isn't importable the script still emits a
manifest SKELETON from KNOWN_SCREENS so you get drop-target screens
immediately, then fills rects once the parser is wired.
"""
import argparse, json, os, shutil, subprocess, sys
from pathlib import Path

# screen -> (layout stem, source archive, output asset folder)
KNOWN_SCREENS = {
    "title":     {"stem": "ui_mainmenu",  "archive": "SystemData",        "ref": [1280, 720]},
    "pause":     {"stem": "ui_pause",     "archive": "SystemCommonCore",  "ref": [1280, 720]},
    "options":   {"stem": "ui_general",   "archive": "SystemCommonCore",  "ref": [1280, 720]},
    "world_map": {"stem": "ui_worldmap",  "archive": "WorldMap",          "ref": [1280, 720]},
    "result":    {"stem": "ui_result",    "archive": "ActionCommon",      "ref": [1280, 720]},
    "boss":      {"stem": "ui_boss_gauge","archive": "BossCommon",        "ref": [1280, 720]},
    "sonic_hud": {"stem": "ui_playscreen","archive": "SonicActionCommon", "ref": [1280, 720]},
    "loading":   {"stem": "ui_loading",   "archive": "Loading",           "ref": [1280, 720]},
}


def run(cmd):
    print("  $", " ".join(str(c) for c in cmd))
    return subprocess.run(cmd, capture_output=True, text=True)


def unpack_archive(hedgearc, archive_path, dest):
    dest.mkdir(parents=True, exist_ok=True)
    r = run([hedgearc, "-E", str(archive_path), "-o", str(dest)])
    if r.returncode != 0:
        print("  ! HedgeArcPack failed:", r.stderr.strip()[:200])
    return dest


def dds_to_png(dds_path, png_path, texconv=None):
    png_path.parent.mkdir(parents=True, exist_ok=True)
    # Prefer texconv (handles BC/DXT) on Windows; fall back to Pillow.
    if texconv:
        r = run([texconv, "-ft", "png", "-o", str(png_path.parent), "-y", str(dds_path)])
        if r.returncode == 0:
            produced = png_path.parent / (dds_path.stem + ".PNG")
            if produced.exists():
                produced.rename(png_path)
            return png_path.exists()
    try:
        from PIL import Image
        Image.open(dds_path).save(png_path)
        return True
    except Exception as e:
        print("  ! DDS->PNG failed for", dds_path.name, "-", e)
        return False


def read_layout_nodes(parser_mod, stem, layout_dir):
    """
    Hook into YOUR .yncp parser. Expected to return a list of:
      { "id": <node name>, "tex": <texture file>, "rect": [x,y,w,h] }
    in 1280x720 reference space. If the parser isn't available, returns
    None and we emit a skeleton instead.
    """
    if not parser_mod:
        return None
    try:
        mod = __import__(parser_mod, fromlist=["parse_layout"])
        return mod.parse_layout(stem, layout_dir)  # implement in your parser
    except Exception as e:
        print("  ! parser hook unavailable (%s); emitting skeleton" % e)
        return None


def emit_manifest(out, screen, info, nodes):
    base = "assets/%s/" % screen
    if nodes is None:
        # skeleton: one full-frame slot the user can drop into, plus a hint
        nodes = [{"id": info["stem"] + "_full", "tex": info["stem"] + ".png",
                  "rect": [0, 0, info["ref"][0], info["ref"][1]], "z": 1, "fit": "contain"}]
    manifest = {
        "screen": screen, "stem": info["stem"], "ref": info["ref"],
        "assetBase": base,
        "notes": "Auto-generated by extract_ui_assets.py from your own copy.",
        "nodes": nodes,
    }
    p = Path(out) / "manifests" / (screen + ".json")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(manifest, indent=2))
    print("  ->", p)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", required=True, help="path to your installed/dumped game dir")
    ap.add_argument("--out", default=".", help="project root to write manifests/ and assets/")
    ap.add_argument("--screens", nargs="*", default=list(KNOWN_SCREENS.keys()))
    ap.add_argument("--hedgearc", default="external_tools/HedgeArcPack/HedgeArcPack.exe")
    ap.add_argument("--texconv", default=shutil.which("texconv"))
    ap.add_argument("--parser", default=None, help="python module exposing parse_layout(stem, dir)")
    args = ap.parse_args()

    work = Path(args.out) / ".extract_work"
    for screen in args.screens:
        if screen not in KNOWN_SCREENS:
            print("skip unknown screen:", screen); continue
        info = KNOWN_SCREENS[screen]
        print("\n=== %s (%s) ===" % (screen, info["stem"]))
        # 1. locate + unpack archive (best-effort; adapt to your layout)
        arc = next(Path(args.game).rglob(info["archive"] + ".ar*"), None)
        layout_dir = work / screen
        if arc:
            unpack_archive(args.hedgearc, arc, layout_dir)
        else:
            print("  ! archive %s.ar* not found under %s" % (info["archive"], args.game))
        # 2-3. read node rects from the .yncp via your parser
        nodes = read_layout_nodes(args.parser, info["stem"], layout_dir)
        # 4. convert each node's DDS -> PNG
        if nodes:
            for n in nodes:
                dds = next(layout_dir.rglob(Path(n["tex"]).stem + ".dds"), None)
                if dds:
                    dds_to_png(dds, Path(args.out) / "assets" / screen / n["tex"], args.texconv)
        # 5. write manifest
        emit_manifest(args.out, screen, info, nodes)

    print("\nDone. Open the viewer and pick the 'Reconstructed' screens.")


if __name__ == "__main__":
    main()
